pipeline {
    agent any
    stages {
        stage('Pact Test') {
            steps {
                dir("billing-service") {
                    sh "./gradlew clean test"
                }
            }
        }
    }
}